# Generated by Django 4.0.3 on 2022-04-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customers_id_remove_users_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='citizenship',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
