# Generated by Django 4.0.3 on 2022-04-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='citizenship',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
    ]
